### ISSUE TITLE
Look up EFS volume by name 

### ISSUE THREAD

**Issue by akibare999** [techservicesillinois/terraform-aws-ec2#12]
Need to be able to look up the EFS volume by English name, not auto-generated ID.

**Comment by JonRoma** [comment]
~See #4. This is a plausible fix.~

**Comment by JonRoma** [comment]
Whoops. I am confounding EFS with EBS.

**Comment by JonRoma** [comment]
I'm sorry to say that this functionality is not supported by either the AWS API for EFS, nor by Terraform. 

AWS doesn't support looking up an EFS filesystem by tag (which would allow us to look up based on a `name`), and only supports the filesystem ID, which of course is randomly selected, and which will vary from account to account. Sorry, but my hands are tied by this rather stupid omission of functionality.

**Comment by JonRoma** [comment]
Now I discover that this capability is technically possible, but there are a lot of "ifs, ands, and buts" that make it less than straightforward. Lookup by tag is possible, but it loses in the event more than one EFS volume has the same "Name" tag. The Terraform to do this is a bit fiddly, so it's not the easy fix I hoped it would be. I'll re-open this but leave it in the queue for later review. It may not be worth the trouble, alas.

**Comment by JonRoma** [comment]
Not having heard any further comment on this, I'm still of the view that this feature would be unreliable and hence not worth the bother.
