### ISSUE TITLE
Deprecation Warning aws_subnet_ids

### ISSUE THREAD

**Issue by zdc217** [techservicesillinois/terraform-aws-ec2#19]
We received the following warning while creating an ec2 instance:

│ Warning: Deprecated Resource
│ 
│   with data.aws_subnet_ids.selected,
│   on data.tf line 21, in data "aws_subnet_ids" "selected":
│   21: data "aws_subnet_ids" "selected" {
│ 
│ The aws_subnet_ids data source has been deprecated and will be removed in a
│ future version. Use the aws_subnets data source instead.

**Comment by JonRoma** [comment]
This is closed by #23.
